### ISSUE TITLE
[vaultwarden] application update >= 1.21.0

### ISSUE THREAD

**Issue by berlincount** [k8s-at-home/charts#1021]
# Details

**Helm chart name:**

vaultwarden

**Describe the solution you'd like:**

updated application version, variables and templates

it seems like too many things changed for a simple version bump to suffice :-/

**Anything else you would like to add:**

I'm too new to Helm myself to be of much use yet, sorry

**Additional Information:**

I love your project <3

**Comment by nicholaswilde** [comment]
Vaultwarden has already been updated to used the latest common library. As for the image version, we don't update each chart for every image release because it'll be too much work for us to keep up with it all! We'd rather spend our time implementing new features and fixing chart bugs. You can see our [FAQ](http://docs.k8s-at-home.com/support/faq/#why-arent-the-charts-updated-with-each-image-release) for an explanation.

Let us know if you have any more questions!

**Comment by berlincount** [comment]
I agree that simple version bumps don't make a lot of sense - in this case, it seems like the whole rename from `bitwarden_rs` to `vaultwarden` was implemented in this version step (don't ask me why this is just a minor version bump instead of a major one).
