### ISSUE TITLE
[owncloud-ocis] application chart

### ISSUE THREAD

**Issue by berlincount** [k8s-at-home/charts#1023]
# Details

**Helm chart name:**

owncloud-ocis

**Describe the solution you'd like:**

there doesn't seem to be any kind of chart for https://owncloud.dev/ocis/deployment/ (owncloud Go reimplementation) yet, but I'd love to use one!

**Anything else you would like to add:**

I'm too new to Helm myself to be of much use yet, sorry

**Additional Information:**

I love your project <3

**Comment by nicholaswilde** [comment]
Thanks for the request! 🙏🏽  Do you happen to know if a multi-architecture container exists for this application? If so, would you mind providing a link?

**Comment by berlincount** [comment]
https://hub.docker.com/layers/owncloud/ocis/latest/images/sha256-bd245d66a4a287c48d4dd16a37ef72df20bea7a0f45f603ae7e5f1143b46e094?context=explore seems perfect :)

it's WIP one way or another, so `latest` might even be appropriate

**Comment by nicholaswilde** [comment]
It looks like [1.7.0](https://hub.docker.com/layers/owncloud/ocis/1.7.0/images/sha256-0ea354ae029f96e426bcfb49bf51de81659c7a0272230557a2760cdafab28ae2?context=explore) supports multi-arch and so we might try to use that one.

**Comment by berlincount** [comment]
what do I need to know? how can I help?

**Comment by nicholaswilde** [comment]
> what do I need to know? how can I help?

You can always create a pull request yourself and submit it and then we can help give you direction. You can start by taking a look at our [docs](http://docs.k8s-at-home.com/our-helm-charts/development/creating-a-new-chart/). Otherwise, you'll have to wait for someone else to create it. We are in the process of updating all of our charts to use to the our latest version of our common library so that's what we've been working on lately. You may also join us on [Discord](https://discord.gg/sTMX7Vh) if you have any questions or if you just want to chat about other stuff.
