### ISSUE TITLE
Catalog not compatible with truenas (k3s)

### ISSUE THREAD

**Issue by spuder** [k8s-at-home/charts#1093]
TrueNas Scale includes kubernetes support using k3s

https://www.truenas.com/truenas-scale/

Unfortunately it appears its not possible to add these charts to a truenas system because the item.yaml files are missing

<img width="1372" alt="Screen Shot 2021-07-18 at 10 47 58 PM" src="https://user-images.githubusercontent.com/242382/126104436-353652a1-b3e7-4274-a04c-668e6c7e7b3c.png">

<img width="825" alt="Screen Shot 2021-07-18 at 10 49 01 PM" src="https://user-images.githubusercontent.com/242382/126104520-450f6c5f-6f0f-4061-bf5c-35d91bb350c6.png">

Comparing to [this helm repository](https://github.com/truenas/charts.git) I suspect an item.yaml might need to be added to each chart

https://github.com/truenas/charts/blob/master/charts/plex/item.yaml

**Comment by bjw-s** [comment]
Hi! Thanks for raising this issue! 

Our charts are aimed primarily at "vanilla" Kubernetes. 
At this time we have no plans to support other platforms, since this would mean adding and maintaining platform-specific files and/or other metadata to our charts. 

For TrueNAS you could take a look at the charts provided by https://github.com/truecharts/apps.
