### ISSUE TITLE
[bookstack] Issue with liveness probe and readiness probe

### ISSUE THREAD

**Issue by aushafy** [k8s-at-home/charts#1104]
# Issue with liveness probe and readiness probe

**Helm chart name and version: k8s-at-home/bookstack 2.3.0**

**Container name and tag: ghcr.io/linuxserver/bookstack:version-v21.05.1**

**What steps did you take and what happened: I just follow the installation step from https://artifacthub.io/packages/helm/k8s-at-home/bookstack**

**Relevant Helm values: https://github.com/k8s-at-home/charts/blob/master/charts/stable/bookstack/values.yaml**

**What did you expect to happen: expect that the installation is very straightforward but there is an issue while deployment pod got crashloopbackoff because of readiness probe and liveness probe failed**

**Additional Information:**
- I deploy bookstack applicaation on GKE version ```Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.19-gke.1701", GitCommit:"d7cecefb99b58e8968f59b59d76448eb1e6ea403", GitTreeState:"clean", BuildDate:"2021-06-23T21:51:59Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}```
- with Helm 3 version ```version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}```
- I also using the external MariaDB configured and already tested from mysql client pod/container inside the kubernetes cluster and it's works successfully

**Solution that I have tried to solve this issue:**
1. The solution that I have tried and run successfully is to add additional configuration for liveness and readiness probe```initialDelaySeconds: 60```

So I think can we discuss to add initialDelaySeconds configuration to the helm template?

**Comment by bjw-s** [comment]
Hi 👋 Thanks for taking the time to write up this issue.

I am not a fan of adding these delays to our charts by default, since they would cause unnecessary wait times before Pods reach a `Ready` state.

All of our charts ((well, almost all of them)) run through a `helm install` phase during the CI and the CI will fail if the application does not reach the `Ready` state in time. I am also running Bookstack in my own cluster (see [here](https://github.com/bjw-s/k8s-gitops/blob/main/cluster/apps/selfhosted/bookstack/helmrelease.yaml) without the need to modify any probe timings.

This being said, that doesn't mean that your cluster doesn't need any modifications to these values. Depending on Kubernetes version, underlying hardware, used resources etc, it can take a Pod more or less time to become `Ready`. 
That is why you can provide your own value overrides through your own `values.yaml` file to tailor the deployment to your needs. Hope this helps explain things a bit.

**Comment by aushafy** [comment]
okay thanks for your reply, I mean is possible if we change the chart template so we can add configuration regarding liveness probe and readiness probe delay or there is any alternative with this?
