### ISSUE TITLE
[teslamate] Bundle teslamate/grafana into the teslamate chart

### ISSUE THREAD

**Issue by phybros** [k8s-at-home/charts#1167]
# Details

**Helm chart name:**

teslamate

**Describe the solution you'd like:**

This chart doesn't seem to bundle a `teslamate/grafana` container, so it doesn't provide all of the functionality of Teslamate as it was intended.

**Anything else you would like to add:**

No

**Additional Information:**

Happy to help if I can, but I'm new to helm.

**Comment by onedr0p** [comment]
What does the `teslamate/grafana` image do?

**Comment by phybros** [comment]
See here https://docs.teslamate.org/docs/installation/docker/

It has preconfigured dashboards - the ones on the Teslamate README.

Without Grafana it's just a place to look at your car in a list lol.

**Comment by onedr0p** [comment]
You can just include the dashboards in a Grafana deployment though?

@billimek does it like this https://github.com/billimek/k8s-gitops/blob/master/monitoring/grafana/grafana.yaml#L175-L230

**Comment by phybros** [comment]
"Just" lol. 

Yeah, I can also create a deployment to run the `teslamate/grafana` image, but using the chart for the first time I assumed there would be a `grafana` section in the values that I could set to `enabled: true` since a chart encapsulates a whole "app" (I thought). 

I could always take a stab at making that a reality?

**Comment by onedr0p** [comment]
I'm not sure how helpful it would be since most of use Grafana for prometheus, loki and to ingest from other sources like influxdb. 

I'd still advise you to run Grafana separately because you don't want it really tied to the lifecycle of teslamate. Once you start tinkering with prometheus, loki, or anything else that's using Grafana as a front end you don't want multiple instances of it.

**Comment by phybros** [comment]
Alrighty then - will close this out
