### ISSUE TITLE
Home-assistant postgres version mismatch

### ISSUE THREAD

**Issue by alongfield** [k8s-at-home/charts#1362]
# Details

This release changes the default postgresql image to 14.x.  This will fail to start for any existing installs due to incompatible database file format versions.

**Helm chart name and version:**

k8s-at-home/home-assistant      12.0.1

**Container name and tag:**
hass-postgresql

values.yaml: 14.1.0 (previously not specified)
Chart.yaml: 10.14.4 (previously 10.14.2)

**What steps did you take and what happened:**

helm upgrade a release using postgresql from before the values.yaml change to 12.0.1.  Postgresql will be unable to start, because a file format upgrade is required before postgres startup.

**Relevant Helm values:**

(from this repo values.yaml)

postgresql:
  image:
    repository: bitnami/postgresql
    tag: 14.1.0

**What did you expect to happen:**

Postgresql would be able to start, either by automatic pg_upgrade, automatic dump/restore job, or a compatible version of the engine.

**Comment by bjw-s** [comment]
Hi! Sorry you ran in to issues with this. 

This change was introduced in [version 12.0.0](https://github.com/k8s-at-home/charts/tree/home-assistant-12.0.0/charts/stable/home-assistant#1200). We intentionally made it a breaking upgrade, because we wanted to indicate that this would not be a "straight-forward" version bump. 

Perhaps we could have included even more details about the upgrade steps that would potentially be required, but since we can not predict the database image version that people were using before (and therefore the exact steps required) we decided against that.

Automatic upgrades of databases are outside the scope of our charts, and would be better targeted at the Bitnami chart we use. Looking through their issues they currently have no plans to implement this, and refer to [other documentation]()https://www.postgresql.org/docs/14/upgrading.html#UPGRADING-VIA-PGDUMPALL as well.
