### ISSUE TITLE
[flood] Default values.yaml leads to unlaunchable flood

### ISSUE THREAD

**Issue by mitchellim** [k8s-at-home/charts#1558]
### Helm chart name

flood

### Helm chart version

6.3.1

### Container name

jesec/flood

### Container tag

4.6.0

### Description

If you try to install the default Flood helm chart, it fails to launch due to:
```
Failed to access runtime directory
```
This is due to its inability to write to the default data directory (per `values.yaml`):
```
  FLOOD_OPTION_RUNDIR: /data
```
However, the directory isn't created by default (also per `values.yaml`):
```
persistence:
  data:
    enabled: false
```
A reasonable default being set would help a lot:
```
persistence:
  data:
    enabled: true
    type: emptyDir
```

### Expected result

Flood launches with sensible defaults.

### Helm values to reproduce

```YAML
N/A (occurs with no YAML changes)
```

**Comment by onedr0p** [comment]
99% of the helm charts here do not work with the default values and this is 'working as intended'. People are expected to fill out their configuration for their app/environment.

Adding a default emptyDir to the values will be even worse UX because the person could not understand what that means, configure the app the way they want in the UI and then when the container restarts they lose everything. It's best to force people to be diligent on configuring the values they need.
