### ISSUE TITLE
[dendrite] Ingress for polylithEnabled

### ISSUE THREAD

**Issue by genofire** [k8s-at-home/charts#1600]
### Helm chart name

dendrite

### Describe the solution you'd like

It would be nice to setup multiple ingress for every dendrite service (with the correct prefix routing)

**Comment by Jonnobrow** [comment]
Hi, thanks for the suggestion. It is something I considered when I first created the polylith version of the chart but it is quite a complex topic so I left it up to the user to implement. When I get a bit more time I will sit down and try to work something out, because I agree that sensible defaults would be good. 😄

**Comment by genofire** [comment]
Hmm, maybe i try it in a month - current i switch from couckroachdb-operator to zalandos PostgreSQl-operator in my private setup: missing backup and nearly every helm-chart does not support PostgreSQL auth per Certificates (instatt passwort)
