### ISSUE TITLE
[Homer] Support for the latest app version

### ISSUE THREAD

**Issue by rstaniek** [k8s-at-home/charts#1713]
### Helm chart name

homer

### Describe the solution you'd like

It would be nice to have the underlying project (Homer) updated to the latest release (22.7.2 as of today) as the current version of the Helm chart (7.2.2) supports only version (21.9.2) from September 2021.

### Additional Information

aforementioned underlying project https://github.com/bastienwirtz/homer

**Comment by bjw-s** [comment]
Hi! You can always override the image that is used by setting your own values for `image.tag`.

We're a relatively small group of people maintaining these charts, so we have chosen not to automatically bump the image tags, but instead rely on community PR's for that since we will never be able to properly gauge what has changed in a certain application version, and what the potential breakage would be.

**Comment by pascaliske** [comment]
Hi @rstaniek,

I can confirm, that the current chart version works with newer Homer releases up to `22.02.2`. So you can simply override the image tag as @bjw-s suggested: `tag: 22.02.2`. But since the maintainer of Homer [reworked the docker integration](https://github.com/bastienwirtz/homer/pull/421), I suppose that newer versions (`22.06.1` and higher) will require some small changes to the Helm chart for proper file permissions on the assets (switch from `UID` & `GID` variables to a `securityContext`).

When I find some time, I will try to build a PR for this...
