### ISSUE TITLE
[zigbee2mqtt] - Old Application Version

### ISSUE THREAD

**Issue by reefland** [k8s-at-home/charts#1745]
### Helm chart name

zigbee2mqtt

### Helm chart version

9.4.2

### Container name

zigbee2mqtt

### Container tag

1.19.1

### Description

The application version is very old, from June 2021. There have been many releases since then.

### Expected result

My understanding is that my install (ArgoCD/Renovate) monitor your chart version, and your project monitors for applicaion updates, then updates the application version and increments the chart version.  If that assumption is correct, then something is broken on this one.

1.27.0 is latest version from 2 weeks ago.
(https://github.com/Koenkk/zigbee2mqtt/releases)

### Helm values to reproduce

```YAML
N/A
```

### Additional Information

Artifact Hub Says the Chart was updated 12 days ago, but the application version is not:
(https://artifacthub.io/packages/helm/k8s-at-home/zigbee2mqtt)

When reviewing the chart history, I can see dozens of revisions but the application version is not increased.

**Comment by bjw-s** [comment]
Your assumption is not correct unfortunately. We do not (automatically) check or monitor for application version updates since those can potentially break things. We leave this to contributors (through PR's) or up to the users to set a custom value for 'image.tag` in their values. (Which can be auto-updates through other tools but that is beyond the scope of this project).
