### ISSUE TITLE
Deduplicating documentation

### ISSUE THREAD

**Issue by DirtyCajunRice** [k8s-at-home/charts#38]
Currently there are significant amounts of documentation duplication which inevitably leads to drift, copy/paste errors, and toil.
Is there a better way? Current thoughts:

Possible remediation options:
* Unique only readmes with common documentatiion in another location
  * docs folder
  * github wiki
  * gh-pages
* Duplicated documentation but the common parts are stitched together by a bot similar to how lsio does their readmes.

In addition, as we lean into artifacthub.io, we will also have a metadata file which will contain basically all of the above information and more. How do we keep the toil down there?

**Comment by carpenike** [comment]
Is there a common standard as to the minimal type of documentation that should be done within the helm chart itself?

**Comment by DirtyCajunRice** [comment]
So i found a pivot point as what you said made me do some digging. Instead of removing docs i went the stitch together route. Its not done but its close. https://github.com/k8s-at-home/charts/commit/7d17666c15926ed507e3a20b3178831434a57179

Command is 
```
gomplate -t ../_helpers.tmpl -c Chart=Chart.yaml -c Values=values.yaml -f ../README.md.tmpl 
```
if you are in the chart's top level dir.

**Comment by billimek** [comment]
IMO the git repo directory for each chart should be the 'source of truth'.  External tooling like artifacthub (or other third-party chart indexers) should reference the chart's readme instead of the other-way-around.

We should be cautious about striving too hard for some form of elegant de-duplication effort at the expense of readability & usability.  Something like https://github.com/k8s-at-home/charts/commit/7d17666c15926ed507e3a20b3178831434a57179 looks like a good starting point for generating initial documentation for a chart, but it would be a mistake, IMO, to adopt a rigid (or overly complicated) standard for README documentation that would prevent adding useful information to a specific chart's README.

**Comment by DirtyCajunRice** [comment]
@billimek I was thinking some kind of modular approach where the template just generated the repo-wide or widely used sections, and then had parts that would be ad-hoc from each section to add whatever you wanted e.g. a file named `UPGRADING.md` with additional upgrade concerns like whats in some charts and it would read the file in as-is. Would this satisfy your concerns for useful uniqueness? If so what other ad-hoc sections should be injectable? I initially assumed additional description, installing, upgrading, and notes.

**Comment by onedr0p** [comment]
I think we should move this discussion over to 

https://github.com/k8s-at-home/charts/discussions
