### ISSUE TITLE
[powerdns] crashlooping: Fatal error: Trying to set unknown parameter 'powerdns-udp-port-53-udp-proto'

### ISSUE THREAD

**Issue by stretched** [k8s-at-home/charts#432]
# Details

**Helm chart name and version:**

powerdns-2.8.0

**Container name and tag:**

naps/powerdns:4.3.1

**What steps did you take and what happened:**

Starting from a clean install with chart default values.
```
$ kubectl create namespace pdns
namespace/pdns created
$ helm install pdns k8s-at-home/powerdns --namespace pdns
```

Postgres server starts up just fine.  powerdns server goes through initial database init, then gets into a crashloop
```
...
Initialized schema version to 4.3.0
Dec 24 08:54:24 Guardian is launching an instance
Dec 24 08:54:24 Fatal error: Trying to set unknown parameter 'powerdns-udp-port-53-udp-proto'
Dec 24 08:54:25 Our pdns instance exited with code 1, respawning
Dec 24 08:54:26 Guardian is launching an instance
Dec 24 08:54:26 Fatal error: Trying to set unknown parameter 'powerdns-udp-port-53-udp-proto'
Dec 24 08:54:27 Our pdns instance exited with code 1, respawning
Dec 24 08:54:28 Guardian is launching an instance
... and so on
```

**What did you expect to happen:**

powerdns should start up and become healthy.

**Anything else you would like to add:**

There's a mismatch in chart metadata versus the default configured container version.
```
$ helm list -n pdns
NAME	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART         	APP VERSION
pdns	pdns     	1       	2020-12-24 19:52:30.18161082 +1100 AEDT	deployed	powerdns-2.8.0	v4.3.0 
```

Verified the container version in the deployment:
```
$ kubectl -n pdns get deployment pdns-powerdns -o yaml
...
        image: naps/powerdns:4.3.1
...
```

**Additional Information:**

I've not been able to find where `powerdns-udp-port-53-udp-proto` is set.  I can't find it in the powerdns chart, or the upstream dockerfile project, or in the powerdns project source code.

I did have this chart deployed and working previously with an older version (sorry, I don't have the version numbers to hand).

Helm and K8s versions
```
$ helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-23T02:22:53Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:00:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by stretched** [comment]
I just noticed the container image repository was changed in dde8baec08bc2b7af1b6f46f64143cbffec7cc29, from `psitrax/powerdns:v4.3.1` to `naps/powerdns:4.3.1`.

Changing the image repository back, and overriding the database settings, and now the powerdns server is healthy.
```
$ kubectl create namespace pdns
namespace/pdns created

$ helm install pdns k8s-at-home/powerdns --namespace pdns --set image.repository=psitrax/powerdns --set image.tag=v4.3.1 --set mariadb.enabled=true --set postgresql.enabled=false
```

Btw, there's a mismatch in Chart.yaml for the postgres depdency.  In Chart.yaml it's written as `condition: postgres.enabled`, while in values.yaml it's 
```
postgresql:
  enabled: true
```

**Comment by NaPs** [comment]
Hi!

FYI I'm the maintainer of the `naps/powerdns:4.3.1` image but not of the helm chart.

Your deployment fail because of two things:

1. A feature introduced by my image that converts all environment variables starting with PDNS_ into powerdns configuration parameters (https://github.com/NaPs/docker-powerdns/blob/master/entrypoint.sh#L185-L192)
2. The fact that Kubernetes inject environment variables into containers for each service in the same namespace (https://kubernetes.io/docs/concepts/containers/container-environment/#cluster-information). In your case, as you named the release `pdns`, services are prefixed with `pdns` (eg: `pdns-powerdns-udp`) and variables are injected into container environment with `PDNS` prefix (eg: `PDNS_POWERDNS_UDP_PORT_53_UDP_PROTO`).

To fix that, I'll need to remove this feature or maintain a whitelist of existing Powerdns configuration parameters instead of simply converting all environment variable with `PDNS` prefix.

To work around this problem, you can simply choose something different than `pdns` for your release name :-)

Note that the psitrax image do not actually works with Postgres, for more information look at this ticket: https://github.com/psi-4ward/docker-powerdns/pull/23

Thank you for catching this bug! :-)

**Comment by stretched** [comment]
Hi @NaPs, 

Changing the release name did indeed fix the crash loop.  Thanks a lot for the pointer!

There's still some other small issues with this chart; I'll work on some PRs for those.
