### ISSUE TITLE
[common] add environment variables to codeserver addon

### ISSUE THREAD

**Issue by c-thiel** [k8s-at-home/charts#436]
**Helm chart name:** common

**Describe the solution you'd like:**
Currently there is no dedicated section for injecting environment variables to VS-Code container.
However, the PASSWORD environment variable is required to enable authentication.

Passing --password has been deprecated and doesn't work with the latest release.

**Comment by bjw-s** [comment]
I thought we already had this in place, and turns out [we did](https://github.com/k8s-at-home/charts/blob/1e46b5c7d62abbd0d3b6bafa617a26969828c995/charts/common/templates/addons/code-server/_container.tpl#L15) but we forgot to include it in the `values.yaml` 😊

Any env variables you specify under `addons.codeserver.env` will get set up in the code-server container.

I've added the example to the next version of `common`.
