### ISSUE TITLE
[common] lower readiness initialDelaySeconds

### ISSUE THREAD

**Issue by Patricol** [k8s-at-home/charts#573]
# Details

**Helm chart name:** common, as well as misc others.

**Describe the solution you'd like:** Don't prevent traffic from being served for 30 seconds by default.

**Anything else you would like to add:** For readiness probes, `initialDelaySeconds=1` and `periodSeconds=5`, or `initialDelaySeconds=5` if keeping `periodSeconds=10`.

**Additional Information:** Until the readiness check succeeds, the pod will not be used to serve traffic. With the current setup, even if pods start and are ready immediately, their services will not be usable for at least 30 seconds, because of the high readiness initial delay. This strikes me as an odd behavior to use as a default for everything. Failed readiness checks do not cause restarts.

The rationale behind my two options is that
* the first checks at `1, 6, 11, 16 ...`, for a max delay of 5 seconds after the start of the app, and a 0-5 second delay in the common case of an app that starts serving after 0.1-4.9 seconds.
* the second checks at `5, 15 ...`, for a max delay of 10 seconds after the start of the app, and a 0-5 second delay in the common case of an app that starts serving after 0.1-4.9 seconds.
* a theoretical bad solution that only changes `initialDelaySeconds=0` but keeps `periodSeconds=10` would check at `0, 10, 20 ...`, for a max delay of 10 seconds after the start of the app, and a 5-10 second delay in the common case of an app that starts serving after 0.1-4.9 seconds.

AFAIK; readiness initialDelaySeconds should only be raised above the default 0 to either
* optimize cycles as described in the bullets above
* not waste packets if you're certain the app will take at least that long to start up
* avoid hitting a badly-designed app with an early request that will cause it to misbehave

Please let me know if I'm misunderstanding something.

Also thank you for this project! It certainly beats needing to maintain 100 homebrew charts/containers myself. Now it's just 50 or so. ;) 

I may open a few PRs to add new charts for services like Wallabag, TT-RSS, and Wekan etc.; which seem to fit this repo nicely.

**Comment by bjw-s** [comment]
Thanks for writing this up, you make a good point! Initially the values were even higher for both liveness and readiness probes (around 60 seconds I think), and we trimmed those down to 30 for both as "safe" default values.

The cases you describe regarding slowish app startup time vs service readiness could be handled by enabling the startupProbe, but we have kept that disabled by default due to API compatibility reasons. 

Maybe it's time to enable it by default, and set the `initialDelay` for both liveness and readiness to 0. That way the startupProbe will indicate that the app is actually "up and running", and after that the other two probes will take over. They should then report success instantly since we kind of already know the app is up and running.

This is a nice writeup on that approach: https://medium.com/tripleuniverse/lets-talk-about-kubernetes-probes-4f850f4d8f81

**Comment by billimek** [comment]
I think it’s time to enable startupProbe by default. The feature was introduced in kubernetes 1.16 from what I recall and it’s been long enough. 

It should be safe to assume that users of these charts will be running 1.16+ IMO.

**Comment by bjw-s** [comment]
👍 I'll create a PR to set this up

**Comment by bjw-s** [comment]
I've created #576. I made it a breaking change, since some defaults are being modified and just in case somebody is running a Kubernetes version that doesn't support the startupProbe.

**Comment by Patricol** [comment]
I wasn't even aware of startupProbes; that's a much better solution @bjw-s; thanks for the info and link!
