### ISSUE TITLE
Deprecate ddclient chart 

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/charts#617]
# Details

**Helm chart name:**

ddclient

**Describe the solution you'd like:**

This chart is not very useful IMO, it's much better suited for a `cronjob` to do ddns updates. i don't think we want to maintain a chart that's a job because it's only like a 20 line YAML file.

**Comment by Ornias1993** [comment]
I agree, there are multiple alternative solutions possible that either:
- Do the same thing beter
- Do the same thing with less code (so less chance of breaking)

**Comment by Patricol** [comment]
@Ornias1993 Do we have charts for any of those?

ddclient supports quite a few DNS providers, and for programatically defined infrastructure, running ddns updates in a container is way better than in some cronjob outside of the environment the rest of the containers run in.

I used ddclient for a few years, but only dropped it because I have proprietary hardware that handles ddns.

**Comment by Ornias1993** [comment]
> than in some cronjob outside of the environment the rest of the containers run in.

Why outside? There are k8s jobs that work (relatively) fine.

About other solutions: thats an unfair question as k8s-at-home ignores a lot of networking related containers for which (official) charts are already available. Which is often the case for these tools..

**Comment by onedr0p** [comment]
Maybe it's a better idea to document different ways at doing ddns, a chart should not be needed for it.

**Comment by Ornias1993** [comment]
@onedr0p Even outside of a k8s perspective such information would be quite valuable for a lot of users :)

**Comment by Patricol** [comment]
> Why outside? There are k8s jobs that work (relatively) fine.

I've somehow have never actually paid attention to the CronJob resource until now. Thank you!

> About other solutions: thats an unfair question as k8s-at-home ignores a lot of networking related containers for which (official) charts are already available. Which is often the case for these tools..

Agreed; just curious what they are, really. I'm not aware of any other tools that support as many DNS providers. My phrasing was mainly shaped by the impression that alternatives were extremely numerous.

**Comment by Patricol** [comment]
I guess my misunderstanding might be philosophical.

What criteria are used when deciding which charts to accept/add or reject/remove?

If ddclient is an actively developed, popular program relevant to the general theme of running k8s at home, implemented with the common chart, and hasn't generated any Issues or even ddclient-specific maintenance commits, it seems like a reasonable inclusion.

Are there official criteria?

Are there actual real disadvantages to using ddclient compared to alternatives; the kind that are noticeable to the user rather than focusing on implementation details?

Granted most of these charts are just a little bit of boilerplate thanks to the common chart's heavy lifting; but discoverability and ease is important when making these technologies more available to the masses.

I'd say that the ease of googling error messages for a well-used program makes it friendlier than debugging a custom cron job too.

**Comment by onedr0p** [comment]
Mainly the issue with the chart is that it runs once and doesn't repetitively do ddns updates which is why a cronjob makes more sense.

**Comment by Patricol** [comment]
> Mainly the issue with the chart is that it runs once and doesn't repetitively do ddns updates which is why a cronjob makes more sense.

Setting `config.daemon=600` in the existing k8s-at-home ddclient chart will make it check every 10 minutes.

**Comment by onedr0p** [comment]
Oh interesting! Maybe we just need to add that to the config example then? But I still feel like this chart is much more suited as a cronjob.

**Comment by Patricol** [comment]
> Oh interesting! Maybe we just need to add that to the config example then?

Opened a PR for it.

> But I still feel like this chart is much more suited as a cronjob.

ddclient being bloated comes in handy when you are stuck with a bad ISP, router, or ISP-provided router.

For those of us privileged enough to have normal setups, yeah basic cronjobs can be good.

**Comment by onedr0p** [comment]
What I mean is you can create a kubernetes cronjob using this ddclient image and use a configmap as the config file. Which is pretty much what this chart is doing sans cronjob.

**Comment by Patricol** [comment]
Ahh, didn't realize that. Is the benefit great enough - or the use case common enough - to justify configuring it as a CronJob in this repo? I haven't looked at the common chart's internals too much; unsure how much extra config would be needed.

**Comment by onedr0p** [comment]
I think it's better not having a chart and just documenting a example cronjob in the wiki.

**Comment by Patricol** [comment]
Seems to use 9MiB on idle. certainly something; but I hesitate to think it's worth special-casing the handling of ddclient for both the maintainers (making a guide or cronjob instead of a chart) or users (reading a separate set of instructions instead of just using the knowledge they have from setting up multiple other k8s-at-home charts.)

I don't think I have too much more to add to the conversation, besides that I still didn't realize that every 'cron job' mention in this whole thread was referring to kubernetes CronJobs; until your last message. Makes more sense now.

**Comment by rgstephens** [comment]
Ran across [this](https://github.com/fschuindt/ddclient/blob/master/k8s/job.yml) kubernetes cronjob config for ddclient.
