### ISSUE TITLE
Add WireGuard

### ISSUE THREAD

**Issue by jr0dd** [k8s-at-home/charts#738]
I would love to see a WireGuard chart in the future. 

https://hub.docker.com/r/linuxserver/wireguard

**Comment by bjw-s** [comment]
Thank you for taking the time to raise this issue. I am closing it though since it does not follow our issue template and does not really have much context about the why (and for example why our VPN addon would not suffice). 

Please use our issue template to provide some more context: https://github.com/k8s-at-home/charts/issues/new?assignees=&labels=kind%3Aenhancement&template=enhancement.md&title=
