### ISSUE TITLE
[stash] pod listening on 0.0.0.0:0 instead of 0.0.0.0:9999

### ISSUE THREAD

**Issue by cranky-coder** [k8s-at-home/charts#893]
# Details

**Helm chart name and version:**
stash 1.2.2

**Container name and tag:**

stashapp/stash:latest

deployed and tried to hit endpoint, endpoint failed.  checked the container logs and the container states its listening on 0.0.0.0:0 instead of 0.0.0.0:9999

*Relevant Helm values:**
all default chart values

**What did you expect to happen:**
Dockerfile indicates that the container should listen on port 9999.  Service in k8s expects the pod to be listening on 9999

This particular environment is pulling this with the arm64 image.

**Comment by onedr0p** [comment]
I am curious is this is app config issue? We run this in CI and it can install and the service/pod reports healthy.

**Comment by cranky-coder** [comment]
It's possible.  But I have completely removed it.  Redeployed with passing only 1 modified value in the helm chart, which is the imagepullpolicy set to always to make sure nothing is cached.  Pod is running.

time="2021-05-07T02:08:27Z" level=info msg="using config file: /root/.stash/config.yml"
INFO[2021-05-07 02:08:29] Migrating database from version 0 to 19
INFO[2021-05-07 02:08:29] Performing vacuum on database
stash version: v0.6.0 (de538be7) - 2021-03-30 07:56:29
INFO[2021-05-07 02:08:30] Version: (de538be7) is already the latest released.
INFO[2021-05-07 02:08:30] stash is listening on 0.0.0.0:0
INFO[2021-05-07 02:08:30] stash is running at http://localhost:0/


the /root/.stash/config.yml is 

calculate_md5: false
config: ""
database: /root/.stash/stash-go.sqlite
generated: ""
host: 0.0.0.0
jwt_secret_key: 362922db7e03bbaa8785f4fd210972df5ffbc0a8b5b8e2cc354be6c87eb78005
parallel_tasks: 1
plugins_path: /root/.stash/plugins
port: tcp://10.43.16.249:9999
preview_exclude_end: "0"
preview_exclude_start: "0"
preview_segment_duration: 0.75
preview_segments: 12
scrapers_path: /root/.stash/scrapers
session_store_key: 221599c3e3d632a2c235646d9e6ed21ea0bafc759ccbcee26322605a4349c7d0
video_file_naming_algorithm: OSHASH


I think I found the issue.  Not 100% how or why.  But on standard docker build and maybe on other clusters the PORT value passed in just the 9999.  But as you can see on the config.yml on this cluster.  It's converted to tcp://<pod ip>:9999  No idea how or why.  But im guessing that's the culprit.

# cat config.yml
calculate_md5: false
config: ""
database: /root/.stash/stash-go.sqlite
generated: ""
host: 0.0.0.0
jwt_secret_key: 4748980d79c40a8ce3635d0a374df94f9e2d0629f3c8afd38c1f7f0d6b008fd5
parallel_tasks: 1
plugins_path: /root/.stash/plugins
port: 9999
preview_exclude_end: "0"
preview_exclude_start: "0"
preview_segment_duration: 0.75
preview_segments: 12
scrapers_path: /root/.stash/scrapers
session_store_key: f3950f19d7b3b254006c77d1700d3ea4676d661e1b8ebbeeb5cf808f5a802cd7
video_file_naming_algorithm: OSHASH

**Comment by slickplaid** [comment]
stash uses `viper`'s `pflag.Int` to pull from the config file (or env variables) and since `port` is a string, it wrongly converts it to `0`.

You can override this until a fix is found by adding the environment variable `STASH_PORT` to a value that matches the `service.port.port` value.

`values.yaml`
from
```yaml
env: {}
```
to
```yaml
env:
  STASH_PORT: 9999
```

Relevant go code:

https://github.com/stashapp/stash/blob/8705f78591a8459c7ea9064fa70e7e6c77cf5d07/pkg/manager/config/init.go#L80
https://github.com/stashapp/stash/blob/8705f78591a8459c7ea9064fa70e7e6c77cf5d07/pkg/manager/config/init.go#L94
https://github.com/stashapp/stash/blob/8705f78591a8459c7ea9064fa70e7e6c77cf5d07/pkg/manager/config/config.go#L359

I haven't quite pinned down how the config.yml file gets generated yet but there's likely some disconnect between always expecting an Int vs passing a connection string somewhere.
